#!/bin/bash

# create jest file

# find `.automated` files and report back the dir
automatedDir=$(ls -A -I node_modules -R | awk '
/:$/&&f{s=$0;f=0}
/:$/&&!f{sub(/:$/,"");s=$0;f=1;next}
NF&&f{ print s"/"$0 }' | pcregrep -o1 '\.\/(.*)\/\.automated\.js')

jestDir=$automatedDir/.automated/jest
mkdir -p $jestDir

echo "/* eslint-disable */
import runner from '@automated/plugin-jest';
import * as config from '../../.automated';
import * as component from '../../';
config.__dirpath = '$automatedDir';
runner({ config, component });" > "$jestDir/__index.js"

###

pwd=`pwd`
jest='/node_modules/@automated/plugin-jest'
bin='/node_modules/.bin/jest'
setupTestFrameworkScriptFile='/lib/setup/setup-test-framework-script-file.js'

# maintain arg quotes - https://stackoverflow.com/a/24179878/537998
function requote() {
  local res=""
  for x in "${@}" ; do
      # try to figure out if quoting was required for the $x:
      grep -q "[[:space:]]" <<< "$x" && res="${res} '${x}'" || res="${res} ${x}"
  done
  # remove first space and print:
  sed -e 's/^ //' <<< "${res}"
}
cliArgs=$(requote "${@}")

jestArgs="
--testRegex=\.automated/jest/.*.js$
--setupTestFrameworkScriptFile=$pwd$jest$setupTestFrameworkScriptFile
"

$pwd$jest$bin$jestArgs$cliArgs
